name: Load Testing

on:
  push:
    branches:
      - main

jobs:
  # Separate job for starting the Flask app
  start_flask_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies (Flask and others from requirements.txt)
        run: pip install -r requirements.txt

      - name: Start Flask application (in background)
        run: nohup python app.py &

  # Separate job for the Locust test
  locust:
    needs: start_flask_app  # Ensures Flask app starts before the test
    runs-on: ubuntu-latest

    env:
      HOST: http://localhost:8000  # Adjust if your app is not running locally
      USERS: 100
      HATCH_RATE: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies (Locust)
        run: pip install locust

      - name: Run load test
        run: |
          locust -f locustfile.py \
            --headless \
            --host=${HOST} \
            --users ${USERS} \
            --spawn-rate ${HATCH_RATE} 