name: Load Testing

on:
  push:
    branches:
      - main

jobs:
  locust:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install locust

      - name: Run load test
        run: locust -f locustfile.py --headless --host=http://localhost:8000