name: Load Testing

on:
  push:
    branches:
      - main

jobs:
  locust:
    runs-on: ubuntu-latest

    env:
      HOST: http://localhost:8000
      USERS: 100
      HATCH_RATE: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install locust
      
      - name: Running app.py
        run: python app.py

      - name: Run load test
        run: python locustfile.py